### ISSUE TITLE
Data.Record conflict - module defined both in purescript-records and purescript-record

### ISSUE THREAD

**Issue by luntain** [doolse/purescript-reactnative#14]
I ran into it by using purescript-quickcheck with purescript-reactnative. The former depends on purescript-record and the latter on purescript-records.

**Comment by dmbfm** [comment]
I was able to fix this issue by using 

```
"purescript-records": "git://github.com/athanclark/purescript-records#214a78e65feda4328ab7245ed8edb10b9b8dd0d8",
"purescript-record": "^0.2.3"
```

in the bower.json file in my fork of purescript-reactnative. I guess we have to wait until these PRs are merged:

https://github.com/purescript/purescript-record/pull/7
https://github.com/doolse/purescript-records/pull/2

**Comment by doolse** [comment]
In 5.0.0 instead of relying on `purescript-records` it now just has it's own `Optional` class. Eventually when `purescript-record` has the required functionality it'll depend on that.
