### ISSUE TITLE
Navigator is deprecated

### ISSUE THREAD

**Issue by dmbfm** [doolse/purescript-reactnative#15]
The `Navigator` component is deprecated in RN > 0.44.0, so it gives an error when trying to use purescript-reactnative with newer versions of React Native.

**Comment by doolse** [comment]
The latest published version (5.0.0) has the navigator and NavigatorExperimental removed. https://github.com/sectore/purescript-react-navigation will eventually get an update for 5.0.0 too

**Comment by jvliwanag** [comment]
Looks like some traces to navigator were left. Submitted #17 for this
