### ISSUE TITLE
Update documentation for v0.12

### ISSUE THREAD

**Issue by omefire** [doolse/purescript-reactnative#24]
It'd be great if we could update the documentation that's on the README.md so that it can pass the v0.12 version of the compiler.

Once I figure things out, I might issue a PR to do just that. For the time being, I'm still trying to figure it out.

**Comment by doolse** [comment]
Thanks for pointing that out. The docs are updated here so it works again. I'll also need to update the `purescript-dispatcher-react` too.

**Comment by omefire** [comment]
@doolse Thanks for handling it so swiftly!
